### PR TITLE
Anti-Aim Refactoring + TODOs

### PR DESCRIPTION
**Pull request by RileyKun**
General anti-aim cleanup and maintenance to improve performance. Adds TODOs to areas that should really see a refactor.

NOTE: I have not tested to see if these changes will compile or how they affect the behaviour of the cheat, as I am having issues with getting my linux virtual machine to display things properly.

### CODE REVIEW

**Comment by FatLardXr41** [comment]
Just Dual-boot, why are you even VMing it?

**Comment by FatLardXr41** [comment]
Will Test em in a bit.

**Comment by RileyKun** [comment]
> Just Dual-boot, why are you even VMing it?

I removed my linux partition as I barely used linux as it is. My machine is more than powerful enough to handle a VM so I thought I would cut back on time by just making a VM. It would also mean I would still have access to my tools and sources that I have on my Windows partition.

**Comment by FatLardXr41** [comment]
Oh, i see.

**Pull request merged**
